# Generated by Django 3.1.3 on 2020-11-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_plants_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pv_plant',
            name='image',
            field=models.ImageField(max_length=250, upload_to='pv_plants'),
        ),
        migrations.AlterField(
            model_name='pv_plant',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
