# Generated by Django 3.1.3 on 2020-12-04 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pv_plants_app', '0006_remove_pv_plant_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pv_plant',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
